// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class LoginTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void login() {
    // Test name: Login
    // Step # | name | target | value
    // 1 | open | / | 
    driver.Navigate().GoToUrl("https://www.facebook.com/");
    // 2 | setWindowSize | 1330x850 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1330, 850);
    // 3 | type | id=email | rajitha.kithuldeniya@gmail.com
    driver.FindElement(By.Id("email")).SendKeys("rajitha.kithuldeniya@gmail.com");
    // 4 | type | id=pass | Ruk@9071
    driver.FindElement(By.Id("pass")).SendKeys("Ruk@9071");
    // 5 | click | id=email | 
    driver.FindElement(By.Id("email")).Click();
    // 6 | click | css=tr:nth-child(2) | 
    driver.FindElement(By.CssSelector("tr:nth-child(2)")).Click();
    // 7 | click | id=pass | 
    driver.FindElement(By.Id("pass")).Click();
    // 8 | click | css=tr:nth-child(2) > td:nth-child(2) | 
    driver.FindElement(By.CssSelector("tr:nth-child(2) > td:nth-child(2)")).Click();
    // 9 | click | id=u_0_b | 
    driver.FindElement(By.Id("u_0_b")).Click();
    // 10 | mouseOver | css=.\_12um:nth-child(2) .\_55lr | 
    {
      var element = driver.FindElement(By.CssSelector(".\\_12um:nth-child(2) .\\_55lr"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 11 | mouseOut | css=.\_12um:nth-child(2) .\_55lr | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    // 12 | mouseOver | css=.\_42fz:nth-child(6) .\_55lr | 
    {
      var element = driver.FindElement(By.CssSelector(".\\_42fz:nth-child(6) .\\_55lr"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    // 13 | mouseOut | css=.\_42fz:nth-child(6) .\_55lr | 
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
  }
}
