// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class SignupTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void signup() {
    // Test name: Signup
    // Step # | name | target | value
    // 1 | open | /signup | 
    driver.Navigate().GoToUrl("https://mail.tutanota.com/signup");
    // 2 | setWindowSize | 1334x854 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1334, 854);
    // 3 | click | css=.button-min-height:nth-child(4) .text-ellipsis | 
    driver.FindElement(By.CssSelector(".button-min-height:nth-child(4) .text-ellipsis")).Click();
    // 4 | click | css=.primary > .text-ellipsis | 
    driver.FindElement(By.CssSelector(".primary > .text-ellipsis")).Click();
    // 5 | click | css=div:nth-child(1) > .text-field > .abs | 
    driver.FindElement(By.CssSelector("div:nth-child(1) > .text-field > .abs")).Click();
    // 6 | type | css=.right | aakithya1988abayakoon
    driver.FindElement(By.CssSelector(".right")).SendKeys("aakithya1988abayakoon");
    // 7 | click | css=div:nth-child(2) > .text-field:nth-child(1) > .abs | 
    driver.FindElement(By.CssSelector("div:nth-child(2) > .text-field:nth-child(1) > .abs")).Click();
    // 8 | type | css=.input:nth-child(4) | VSzhk.83978
    driver.FindElement(By.CssSelector(".input:nth-child(4)")).SendKeys("VSzhk.83978");
    // 9 | click | css=.text-field:nth-child(3) > .abs | 
    driver.FindElement(By.CssSelector(".text-field:nth-child(3) > .abs")).Click();
    // 10 | type | css=.text-field:nth-child(3) .input | VSzhk.83978
    driver.FindElement(By.CssSelector(".text-field:nth-child(3) .input")).SendKeys("VSzhk.83978");
    // 11 | click | css=div > .checkbox:nth-child(3) input | 
    driver.FindElement(By.CssSelector("div > .checkbox:nth-child(3) input")).Click();
    // 12 | click | css=.checkbox:nth-child(4) input | 
    driver.FindElement(By.CssSelector(".checkbox:nth-child(4) input")).Click();
    // 13 | click | css=.mt-l .text-ellipsis | 
    driver.FindElement(By.CssSelector(".mt-l .text-ellipsis")).Click();
    // 14 | type | css=.plr-l > .text-field .input | 04:50
    driver.FindElement(By.CssSelector(".plr-l > .text-field .input")).SendKeys("04:50");
    // 15 | click | css=.primary > .text-ellipsis | 
    driver.FindElement(By.CssSelector(".primary > .text-ellipsis")).Click();
    // 16 | click | css=.monospace | 
    driver.FindElement(By.CssSelector(".monospace")).Click();
    // 17 | click | css=.monospace | 
    driver.FindElement(By.CssSelector(".monospace")).Click();
    // 18 | click | css=.flex > .limit-width:nth-child(1) > .button-content svg | 
    driver.FindElement(By.CssSelector(".flex > .limit-width:nth-child(1) > .button-content svg")).Click();
    // 19 | click | css=div:nth-child(1) > .full-width > .button-content | 
    driver.FindElement(By.CssSelector("div:nth-child(1) > .full-width > .button-content")).Click();
    // 20 | click | css=.text-field:nth-child(2) .input | 
    driver.FindElement(By.CssSelector(".text-field:nth-child(2) .input")).Click();
    // 21 | click | css=.text-field:nth-child(2) .input | 
    driver.FindElement(By.CssSelector(".text-field:nth-child(2) .input")).Click();
    // 22 | type | css=.text-field:nth-child(2) .input | VSzhk.83978
    driver.FindElement(By.CssSelector(".text-field:nth-child(2) .input")).SendKeys("VSzhk.83978");
    // 23 | click | css=.login | 
    driver.FindElement(By.CssSelector(".login")).Click();
  }
}
